#!/bin/sh
#
# openvpn.sh - load tun/tap driver and start OpenVPN daemon
#

# PROVIDE: openvpn
# REQUIRE: DAEMON
# KEYWORD: shutdown

# -----------------------------------------------------------------------------
#
# Additional variables defined in /etc/rc.conf.d/openvpn
#
# For further documentation, please see openvpn(8).
#

. /etc/rc.subr

# service(8) does not create an authentic environment, try to guess,
# and as of 10.3-RELEASE-p0, it will not find the indented name=
# assignments below. So give it a default.
# Trailing semicolon also for service(8)'s benefit:
name="$file" ;

case "$0" in
/etc/rc*)
  # during boot (shutdown) $0 is /etc/rc (/etc/rc.shutdown),
  # so get the name of the script from $_file
  name="$_file"
  ;;
*/service)
  # do not use this as $0
  ;;
*)
  name="$0"
  ;;
esac

# Default name to "openvpn" if guessing failed
# Trailing semicolon also for service(8)'s benefit:
name="${name:-openvpn}" ;
name="${name##*/}"
rcvar=${name}_enable

# reload: support SIGHUP to reparse configuration file
# softrestart: support SIGUSR1 to reconnect without superuser privileges
# stats: support SIGUSR2 to write statistics to the syslog
extra_commands="reload softrestart stats"
softrestart_cmd="softrestart"
stats_cmd="openvpn_stats"
start_precmd="openvpn_prestart"

# run this last
stop_postcmd="stop_postcmd"

stop_postcmd()
{
  rm -f "$pidfile" || warn "Could not remove $pidfile."
}

softrestart()
{
  sig_reload=USR1 run_rc_command reload
  exit $?
}

openvpn_stats()
{
  sig_reload=USR2
  run_rc_command ${rc_prefix}reload $rc_extra_args
}

openvpn_prestart()
{
  # Getting a random recommended NordVPN server
  URL="https://api.nordvpn.com/server"
  SERVER=$(/usr/local/bin/curl -s "$URL" | /usr/local/bin/jq -r '.[] | select(.search_keywords | index("P2P")) | .domain' | sort -R | head -n1)
  SERVER_FILE="https://downloads.nordcdn.com/configs/files/ovpn_udp/servers/${SERVER}.udp.ovpn"
  echo "Chosen: ${SERVER_FILE}"
  /usr/local/bin/curl -s "${SERVER_FILE}" -o "/usr/local/etc/openvpn/client.conf"

  # Getting a random recommended NordVPN server

  URL="https://nordvpn.com/wp-admin/admin-ajax.php?action=servers_recommendations"
  SERVER=$(/usr/local/bin/curl -s "$URL" --globoff | /usr/local/bin/jq -r '.[].hostname' | sort --random-sort | head -n 1)
  /usr/local/bin/wget -q "https://downloads.nordcdn.com/configs/files/ovpn_tcp/servers/${SERVER}.tcp.ovpn" -O "/usr/local/etc/openvpn/client.conf"

  return 0
}

# pidfile
pidfile="/var/run/${name}.pid"

# command and arguments
command="/usr/local/sbin/openvpn"

load_rc_config ${name}

eval ": \${${name}_enable:=\"NO\"}"
eval ": \${${name}_configfile:=\"/usr/local/etc/openvpn/${name}.conf\"}"
eval ": \${${name}_dir:=\"/usr/local/etc/openvpn\"}"

configfile="$(eval echo \${${name}_configfile})"
dir="$(eval echo \${${name}_dir})"
interfaces="$(eval echo \${${name}_if})"

required_modules=
for i in $interfaces ; do
    required_modules="$required_modules${required_modules:+" "}if_${i#if_}"
done

required_files=${configfile}

command_args="--cd ${dir} --daemon ${name} --writepid ${pidfile} --config ${configfile} --config /usr/local/etc/openvpn/override.conf"

run_rc_command "$1"
